#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
out_file="$script_dir/hosts/p15v/gpu-bus-ids.nix"

require_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "error: required command not found: $1" >&2
        exit 1
    fi
}

hex_to_dec() {
    printf '%d' "0x$1"
}

pci_to_nixos_bus_id() {
    pci_addr="$1"

    domain_and_bus=${pci_addr%:*}
    device_and_func=${pci_addr##*:}

    bus_hex=${domain_and_bus##*:}
    device_hex=${device_and_func%.*}
    func_hex=${device_and_func##*.}

    printf 'PCI:%s:%s:%s' \
        "$(hex_to_dec "$bus_hex")" \
        "$(hex_to_dec "$device_hex")" \
        "$(hex_to_dec "$func_hex")"
}

find_gpu_addr() {
    vendor_id="$1"

    lspci -Dnn | awk -v vendor="$vendor_id" '
        /\[(0300|0302)\]/ && $0 ~ "\\[" vendor ":" {
            print $1
            exit
        }
    '
}

require_cmd lspci
require_cmd awk

amd_addr=$(find_gpu_addr 1002 || true)
nvidia_addr=$(find_gpu_addr 10de || true)

if [ -z "$amd_addr" ]; then
    echo "error: could not find an AMD GPU in lspci output" >&2
    exit 1
fi

if [ -z "$nvidia_addr" ]; then
    echo "error: could not find an NVIDIA GPU in lspci output" >&2
    exit 1
fi

amd_bus_id=$(pci_to_nixos_bus_id "$amd_addr")
nvidia_bus_id=$(pci_to_nixos_bus_id "$nvidia_addr")

cat > "$out_file" <<EOF
{
  # Generated by detect-gpu-bus-ids.sh on $(date -Iseconds)
  amdgpuBusId = "$amd_bus_id";
  nvidiaBusId = "$nvidia_bus_id";
}
EOF

printf 'Saved %s\n' "$out_file"
printf '  amdgpuBusId = %s\n' "$amd_bus_id"
printf '  nvidiaBusId = %s\n' "$nvidia_bus_id"
